name: Build Ergohaven OP36 (both halves)
on:
  workflow_dispatch: {}

jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["ergohaven"]'
      shield: '["op36_left","op36_right"]'
      alphas: '["QWERTY"]'
      nav: '["default"]'
      layers: '["default"]'
      mapping: '["default"]'
      custom_config: '["#define MIRYOKU_CLIPBOARD_WIN\n#define MIRYOKU_EXTRA_COLEMAKDH\n#define MIRYOKU_TAP_QWERTY"]'
      kconfig: '["CONFIG_ZMK_POINTING=y"]'
      branches: '["default"]'      # leave unless you need a custom ZMK branch merge
      modules: '["default"]'

